language: python
python:
  - "2.7"
install:
  - pip install -r app/test-requires --use-mirrors
  - pip install coveralls
before_script:
  - cd app
script:
  - coverage run --source=core,run setup.py nosetests
after_success:
  - coveralls
